
neat_config: "config/neat.ini"  # retained but unused (training generates runs/neat_config.ini with dynamic input size)

data:
  dataset: "truthfulqa"
  val_frac: 0.2
  test_frac: 0.2
  bank_frac: 0.6
  seed: 42

selector:
  embedding: "sentence-transformers/all-MiniLM-L6-v2"
  shortlist: 64
  sim_cap: 32
  K: 6
  alpha: 0.5
  mmr_lambda: 0.3

evolution:
  micro_batches: 4
  batch_size: 8
  early_stop_patience: 5

prompt:
  pop_size: 10
  generations: 6
  elite_k: 2

judge:
  repeats: 1
  model: "llama3.2:3b"
  base_url: "http://localhost:11434/"
  temperature: 0.0
