
neat_config: "config/neat.ini"
data:
  dataset: "truthfulqa"
  val_frac: 0.1
  test_frac: 0.1
  bank_frac: 0.6
  seed: 42
selector:
  embedding: "sentence-transformers/all-MiniLM-L6-v2"
  shortlist: 64
  sim_cap: 32
  K: 6
  alpha: 0.5
  mmr_lambda: 0.3
evolution:
  generations: 5
  micro_batches: 6
  batch_size: 8
  early_stop_patience: 5
judge:
  repeats: 2
  model: "llama3.2:3b"
  base_url: "http://localhost:11434/"
  temperature: 0.0
